### ISSUE TITLE
An error has occured while running client example "peer closed connection without sending complete message body (incomplete chunked read)"

### ISSUE THREAD

**Issue by plt12138** [npuichigo/openai_trtllm#31]
I build a Mixtral modle in TensorRT-LLM v0.8.0 and run tensorrtllm_backend ok. HTTP port is 8000:
```
+----------------------------------+------------------------------------------------------------------------------------+
| Option                           | Value                                                                              |
+----------------------------------+------------------------------------------------------------------------------------+
| server_id                        | triton                                                                             |
| server_version                   | 2.43.0                                                                             |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) sched |
|                                  | ule_policy model_configuration system_shared_memory cuda_shared_memory binary_tens |
|                                  | or_data parameters statistics trace logging                                        |
| model_repository_path[0]         | triton_model_repo/                                                                 |
| model_control_mode               | MODE_NONE                                                                          |
| strict_model_config              | 1                                                                                  |
| rate_limit                       | OFF                                                                                |
| pinned_memory_pool_byte_size     | 268435456                                                                          |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                           |
| cuda_memory_pool_byte_size{1}    | 67108864                                                                           |
| cuda_memory_pool_byte_size{2}    | 67108864                                                                           |
| cuda_memory_pool_byte_size{3}    | 67108864                                                                           |
| min_supported_compute_capability | 6.0                                                                                |
| strict_readiness                 | 1                                                                                  |
| exit_timeout                     | 30                                                                                 |
| cache_enabled                    | 0                                                                                  |
+----------------------------------+------------------------------------------------------------------------------------+

I0325 06:40:07.883386 2825 grpc_server.cc:2519] Started GRPCInferenceService at 0.0.0.0:8001
I0325 06:40:07.883628 2825 http_server.cc:4637] Started HTTPService at 0.0.0.0:8000
I0325 06:40:07.926222 2825 http_server.cc:320] Started Metrics Service at 0.0.0.0:8002
```
And run this project by commad `./target/release/openai_trtllm -t http://localhost:8000` ：
```
(base) [root@localhost openai_trtllm]# ./target/release/openai_trtllm -t http://localhost:8000 
{"timestamp":"2024-03-25T07:44:19.597226Z","level":"INFO","message":"Connecting to triton endpoint: http://localhost:8000","target":"openai_trtllm::startup"}
{"timestamp":"2024-03-25T07:44:19.598900Z","level":"INFO","message":"Starting server at 0.0.0.0:3000","target":"openai_trtllm::startup"}
```

Then I want to try client example `openai_completion_stream.py` but get error :
```
(base) [root@localhost client]# python openai_completion_stream.py 
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 111, in __iter__
    for part in self._httpcore_stream:
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 361, in __iter__
    for part in self._stream:
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 337, in __iter__
    raise exc
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 329, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 198, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/root/miniconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/zht/openai_trtllm/client/openai_completion_stream.py", line 13, in <module>
    for event in response:
  File "/root/miniconda3/lib/python3.11/site-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/root/miniconda3/lib/python3.11/site-packages/openai/_streaming.py", line 61, in __stream__
    for sse in iterator:
  File "/root/miniconda3/lib/python3.11/site-packages/openai/_streaming.py", line 53, in _iter_events
    yield from self._decoder.iter(self.response.iter_lines())
  File "/root/miniconda3/lib/python3.11/site-packages/openai/_streaming.py", line 287, in iter
    for line in iterator:
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 863, in iter_lines
    for text in self.iter_text():
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 850, in iter_text
    for byte_content in self.iter_bytes():
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_models.py", line 887, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_client.py", line 124, in __iter__
    for chunk in self._stream:
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 110, in __iter__
    with map_httpcore_exceptions():
  File "/root/miniconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
(base) [root@localhost client]# 
```

openai_trtllm output:
```
{"timestamp":"2024-03-25T07:44:25.888009Z","level":"INFO","message":"request: Json(CompletionCreateParams { model: \"ensemble\", prompt: [\"This is a story of a hero who went\"], best_of: 1, echo: false, frequency_penalty: 0.0, logit_bias: None, logprobs: None, max_tokens: 50, n: 1, presence_penalty: 0.0, seed: None, stop: None, stream: true, suffix: None, temperature: 1.0, top_p: 1.0, user: None })","target":"openai_trtllm::routes::completions","span":{"headers":"{\"host\": \"localhost:3000\", \"accept-encoding\": \"gzip, deflate, br\", \"connection\": \"keep-alive\", \"accept\": \"application/json\", \"content-type\": \"application/json\", \"user-agent\": \"OpenAI/Python 1.14.2\", \"x-stainless-lang\": \"python\", \"x-stainless-package-version\": \"1.14.2\", \"x-stainless-os\": \"Linux\", \"x-stainless-arch\": \"x64\", \"x-stainless-runtime\": \"CPython\", \"x-stainless-runtime-version\": \"3.11.4\", \"authorization\": \"Bearer test\", \"x-stainless-async\": \"false\", \"content-length\": \"103\"}","name":"completions"},"spans":[{"http.request.method":"POST","http.route":"/v1/completions","network.protocol.version":"1.1","otel.kind":"Server","otel.name":"POST /v1/completions","server.address":"localhost:3000","span.type":"web","url.path":"/v1/completions","url.scheme":"","user_agent.original":"OpenAI/Python 1.14.2","name":"HTTP request"},{"headers":"{\"host\": \"localhost:3000\", \"accept-encoding\": \"gzip, deflate, br\", \"connection\": \"keep-alive\", \"accept\": \"application/json\", \"content-type\": \"application/json\", \"user-agent\": \"OpenAI/Python 1.14.2\", \"x-stainless-lang\": \"python\", \"x-stainless-package-version\": \"1.14.2\", \"x-stainless-os\": \"Linux\", \"x-stainless-arch\": \"x64\", \"x-stainless-runtime\": \"CPython\", \"x-stainless-runtime-version\": \"3.11.4\", \"authorization\": \"Bearer test\", \"x-stainless-async\": \"false\", \"content-length\": \"103\"}","name":"completions"}]}
```

**Comment by plt12138** [comment]
Same error occured at `openai_completion.py` and `langchain_openai.py` get error:
```
(base) [root@localhost client]# python langchain_openai.py
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: 'An error occurred while trying to fulfill your request.' (HTTP response code was 500).

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: 'An error occurred while trying to fulfill your request.' (HTTP response code was 500).

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: 'An error occurred while trying to fulfill your request.' (HTTP response code was 500).
```

**Comment by plt12138** [comment]
Could this problem be the cause of the model type? Is this project only applicable to Baichuan?

**Comment by npuichigo** [comment]
The repo is not llama specific. It’s recommended to use https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/end_to_end_grpc_client.py with/without streaming to test trtllm backend first.

**Comment by plt12138** [comment]
Test trtllm backend use end_to_end_grpc_client.py with/without streaming seems  ok :
```
root@3090-node2:/tensorrtllm_backend/inflight_batcher_llm/client# python3 end_to_end_grpc_client.py  --output-len 20 --prompt "The only thing we have to fear is"

[b'The only thing we have to fear is fear itself.\xe2\x80\x9d\n\nThe quote is from Franklin Delano Roosevelt\xe2\x80\x99s first inaugural address in']
root@3090-node2:/tensorrtllm_backend/inflight_batcher_llm/client# 
root@3090-node2:/tensorrtllm_backend/inflight_batcher_llm/client# 
root@3090-node2:/tensorrtllm_backend/inflight_batcher_llm/client# python3 end_to_end_grpc_client.py  --streaming --output-len 20 --prompt "The only thing we have to fear is"
The only thing we have to fear is fear itself.”

The quote is from Franklin Delano Roosevelt’s first inaugural address in
root@3090-node2:/tensorrtllm_backend/inflight_batcher_llm/client#
```

**Comment by npuichigo** [comment]
Could u set `RUST_LOG=debug` to run `openai_trtllm` and provide the error message of both openai_completion.py and the server? By the way, which model do you use?

**Comment by plt12138** [comment]
> RUST_LOG=debug

Thank. I got the error:
```
(base) [root@localhost openai_trtllm]# RUST_LOG=debug ./target/release/openai_trtllm -t http://localhost:8000
{"timestamp":"2024-03-26T08:30:55.526610Z","level":"INFO","message":"Connecting to triton endpoint: http://localhost:8000","target":"openai_trtllm::startup"}
{"timestamp":"2024-03-26T08:30:55.526800Z","level":"DEBUG","message":"resolving host=\"localhost\"","target":"hyper::client::connect::dns"}
{"timestamp":"2024-03-26T08:30:55.527373Z","level":"DEBUG","message":"connecting to [::1]:8000","target":"hyper::client::connect::http"}
{"timestamp":"2024-03-26T08:30:55.527465Z","level":"DEBUG","message":"connecting to 127.0.0.1:8000","target":"hyper::client::connect::http"}
{"timestamp":"2024-03-26T08:30:55.527544Z","level":"DEBUG","message":"connected to 127.0.0.1:8000","target":"hyper::client::connect::http"}
{"timestamp":"2024-03-26T08:30:55.527576Z","level":"DEBUG","message":"binding client connection","target":"h2::client"}
{"timestamp":"2024-03-26T08:30:55.527599Z","level":"DEBUG","message":"client connection bound","target":"h2::client"}
{"timestamp":"2024-03-26T08:30:55.527619Z","level":"DEBUG","message":"send","frame":"Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }","target":"h2::codec::framed_write"}
{"timestamp":"2024-03-26T08:30:55.527833Z","level":"DEBUG","message":"connection error: not connected","target":"hyper::proto::h2::client"}
{"timestamp":"2024-03-26T08:30:55.527871Z","level":"DEBUG","message":"connection error: hyper::Error(Io, Custom { kind: BrokenPipe, error: \"connection closed because of a broken pipe\" })","target":"hyper::client::service"}
{"timestamp":"2024-03-26T08:30:55.528017Z","level":"INFO","message":"Starting server at 0.0.0.0:3000","target":"openai_trtllm::startup"}
```
Seems I need use `-t ` to connect triton grpc port 8001.

**Comment by plt12138** [comment]
> Could u set `RUST_LOG=debug` to run `openai_trtllm` and provide the error message of both openai_completion.py and the server? By the way, which model do you use?

I'm using Mixtral-8x7b

**Comment by npuichigo** [comment]
> > RUST_LOG=debug
> 
> Thank. I got the error:
> 
> ```
> (base) [root@localhost openai_trtllm]# RUST_LOG=debug ./target/release/openai_trtllm -t http://localhost:8000
> {"timestamp":"2024-03-26T08:30:55.526610Z","level":"INFO","message":"Connecting to triton endpoint: http://localhost:8000","target":"openai_trtllm::startup"}
> {"timestamp":"2024-03-26T08:30:55.526800Z","level":"DEBUG","message":"resolving host=\"localhost\"","target":"hyper::client::connect::dns"}
> {"timestamp":"2024-03-26T08:30:55.527373Z","level":"DEBUG","message":"connecting to [::1]:8000","target":"hyper::client::connect::http"}
> {"timestamp":"2024-03-26T08:30:55.527465Z","level":"DEBUG","message":"connecting to 127.0.0.1:8000","target":"hyper::client::connect::http"}
> {"timestamp":"2024-03-26T08:30:55.527544Z","level":"DEBUG","message":"connected to 127.0.0.1:8000","target":"hyper::client::connect::http"}
> {"timestamp":"2024-03-26T08:30:55.527576Z","level":"DEBUG","message":"binding client connection","target":"h2::client"}
> {"timestamp":"2024-03-26T08:30:55.527599Z","level":"DEBUG","message":"client connection bound","target":"h2::client"}
> {"timestamp":"2024-03-26T08:30:55.527619Z","level":"DEBUG","message":"send","frame":"Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }","target":"h2::codec::framed_write"}
> {"timestamp":"2024-03-26T08:30:55.527833Z","level":"DEBUG","message":"connection error: not connected","target":"hyper::proto::h2::client"}
> {"timestamp":"2024-03-26T08:30:55.527871Z","level":"DEBUG","message":"connection error: hyper::Error(Io, Custom { kind: BrokenPipe, error: \"connection closed because of a broken pipe\" })","target":"hyper::client::service"}
> {"timestamp":"2024-03-26T08:30:55.528017Z","level":"INFO","message":"Starting server at 0.0.0.0:3000","target":"openai_trtllm::startup"}
> ```
> 
> Seems I need use `-t ` to connect triton grpc port 8001.

My fault, I should mention that `openai_trtllm` communicate with the triton inference server over gRPC.

**Comment by plt12138** [comment]
Thanks. gRPC port works. 
But my model doesn't streaming output. Not even script `end_to_end_grpc_client.py` and `inflight_batcher_llm_client.py` in triron. 
Do you know how to startup trtllm backend to support streaming mode? I've already setup option `decoupled_mode:true`.

**Comment by npuichigo** [comment]
@plt12138 the document in tensorrtllm backend mentions how to enable streaming (for example, set decoupled to true). You can check it.
